name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags, e.g., v1.0.0
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build:
    name: Build for Multiple Platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin] # Target operating systems
        goarch: [amd64, arm64]         # Target architectures

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # Specify a Go version that supports modules

      - name: Download dependencies
        run: |
          go mod tidy

      - name: Build binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/nomi-cli-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nomi-cli-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/nomi-cli-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
